# fly.toml app configuration file generated for atlis-landing-deprecated on 2023-08-01T09:01:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "atlis-landing-deprecated"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["npm run dev"]

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
